# Travis CI configuration for setproctitle

language: python

matrix:
  include:

    - env: TOXENV=py36
      python: 3.6

    - env: TOXENV=py37
      python: 3.7

    - env: TOXENV=py38
      python: 3.8


install:
  - pip install tox


script:
  - tox
